import Head from "next/head";

import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Login from "../components/Login";
import Game from "../components/Game";
import Header from "@/components/Header";
import GameRules from "@/components/GameRules";

export default function Home() {
  const [isLogged, setIsLogged] = useState(false);

  return (
    <>
      <Head>
        <title>Wheel of fortune</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header {...{ isLogged, setIsLogged }} />
        <div className={styles.gameContainer}>
          <div className={styles.gameLeftContainer}>
            {isLogged ? (
              <Game {...{ setIsLogged }} />
            ) : (
              <Login {...{ setIsLogged }} />
            )}
          </div>
          <GameRules />
        </div>
      </main>
    </>
  );
}
